### PR TITLE
Heatmap

### LINKED ISSUE #14: Heatmap

### PR DESCRIPTION
**Pull request by rbjansen**

### CODE REVIEW

**Review by Peder2911 — CHANGES_REQUESTED** [review]
I don't really understand how to get a plot from this one. Could you provide an example @rbjansen? Running with a time-unit (priogrid - month) indexed series from months 1:10 produces an empty plot that looks like this:

**Comment by Peder2911** [comment]
plt

**Comment by Peder2911** [comment]
What would really help would be to have a code example that fetches data with viewser and produces the plot.

**Comment by rbjansen** [comment]
@hhegre @Peder2911 I have revised the code and added some examples in the notebook [here](https://github.com/prio-data/views_dataviz/blob/b23869450187c14b4b40555d9cf19b77b00b762b/examples/heatmap.ipynb)

**Pull request merged**
